apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-gpu
spec:
  nodeSelector:
    gpu: "true"
  containers:
    - image: krk224tmax/kubia:amd
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP