apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v1
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels: 
        app: kubia
    spec:
      containers:
      - name: nodejs
        image: krk224tmax/kubia:v1
        ports:
        - containerPort: 8080
          name: default-http
---
apiVersion: v1
kind: Service
metadata:
  name: kubia-svc
spec:
  type: LoadBalancer
  selector:
    app: kubia
  ports:
  - port: 80
    targetPort: default-http