apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  namespace: downward
spec:
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job

