apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-from-configmap
  labels:
    app: fortune
    type: configmap
spec:
  containers:
  - image: krk224tmax/fortune:env
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    imagePullPolicy: Always
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    - name: NODE_ENV
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: env
          option: true
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
